apiVersion: v1
kind: Service
metadata:
  name:  {{ template "habitat-builder.fullname" . }}-api-ext
  labels:
    app: {{ template "habitat-builder.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: 80
{{- if .Values.app.ssl.enabled }}
  - name: https
    port: 443
{{- end }}
  selector:
    habitat-name: {{ template "habitat-builder.fullname" . }}-api-proxy