apiVersion: v1
kind: Service
metadata:
  name:  {{ template "habitat-builder.fullname" . }}-minio-int
  labels:
    app: {{ template "habitat-builder.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
  selector:
    habitat-name: {{ template "habitat-builder.fullname" . }}-minio
