{{- if .Values.debug }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "habitat-builder.fullname" . }}-minio-ext
  labels:
    app: "{{ template "habitat-builder.name" . }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 9000
  selector:
    habitat-name:  {{ template "habitat-builder.fullname" . }}-minio
{{- end }}