variable "aws_region" {}
variable "aws_profile" {}
variable "aws_key_pair_file" {}
variable "aws_key_pair_name" {}
variable "aws_image_user" {}
variable "habitat_origin" {}
variable "env" {}
variable "bldr_url" {}
variable "release_channel" {}
variable "group" {}
variable "update_strategy" {}
variable "tag_dept" {}
variable "tag_customer" {}
variable "tag_project" {}
variable "tag_application" {}
variable "tag_contact" {}
variable "tag_ttl" {}
